# App Config
spring.application.name=SmartHire
server.port=8080

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/smarthire_db
spring.datasource.username=root
spring.datasource.password=Root@2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect